Repository Nexters/pinata-server, pull requests merged in 2022-08, with the labels that each got.

#21 [Refactoring] signup, signin request 수정 및 jwt subject 변경
  src/main/java/com/nexters/pinataserver/auth/controller/AuthorizeController.java
  src/main/java/com/nexters/pinataserver/auth/dto/request/SignInRequest.java
  src/main/java/com/nexters/pinataserver/auth/service/AuthService.java
  src/main/java/com/nexters/pinataserver/common/config/WebMvcConfig.java
  src/main/java/com/nexters/pinataserver/common/dto/response/CommonApiResponse.java
  src/main/java/com/nexters/pinataserver/common/exception/ExceptionControllerAdvice.java
  src/main/java/com/nexters/pinataserver/common/exception/ResponseException.java
  src/main/java/com/nexters/pinataserver/common/exception/e4xx/AuthenticationException.java
  src/main/java/com/nexters/pinataserver/common/exception/e4xx/NotFoundException.java
  src/main/java/com/nexters/pinataserver/common/filter/CorsFilter.java
  src/main/java/com/nexters/pinataserver/common/interceptor/JwtInterceptor.java
  src/main/java/com/nexters/pinataserver/common/security/AuthenticationArgumentResolver.java
  src/main/java/com/nexters/pinataserver/common/security/JwtService.java
  src/main/java/com/nexters/pinataserver/event/domain/EventDateTime.java
  src/main/java/com/nexters/pinataserver/event/service/EventReadService.java
  src/main/java/com/nexters/pinataserver/user/domain/UserRepository.java
  src/main/java/com/nexters/pinataserver/user/service/UserService.java
Labels: ⚙️ refactoring

#20 ✨ feat : 이벤트 생성 API 구현
  src/main/java/com/nexters/pinataserver/common/exception/ExceptionControllerAdvice.java
  src/main/java/com/nexters/pinataserver/common/exception/e4xx/DuplicatedException.java
  src/main/java/com/nexters/pinataserver/common/exception/e4xx/EventStatusException.java
  src/main/java/com/nexters/pinataserver/common/validation/EnumValidator.java
  src/main/java/com/nexters/pinataserver/common/validation/ValidEnum.java
  src/main/java/com/nexters/pinataserver/event/controller/EventController.java
  src/main/java/com/nexters/pinataserver/event/domain/Event.java
  src/main/java/com/nexters/pinataserver/event/dto/request/RegisterEventRequest.java
  src/main/java/com/nexters/pinataserver/event/dto/response/RegisterEventResponse.java
  src/main/java/com/nexters/pinataserver/event/service/EventCreateService.java
  src/main/java/com/nexters/pinataserver/event/service/EventParticipateService.java
Labels: 🏄🏻‍♂️ feature

#23 [Feature] 유저 정보 조회 API 생성
  src/main/java/com/nexters/pinataserver/auth/controller/AuthorizeController.java
  src/main/java/com/nexters/pinataserver/auth/dto/request/SignUpRequest.java
  src/main/java/com/nexters/pinataserver/auth/dto/response/SignUpResponse.java
  src/main/java/com/nexters/pinataserver/user/controller/UserController.java
  src/main/java/com/nexters/pinataserver/user/dto/UserResponse.java
  src/main/java/com/nexters/pinataserver/user/service/UserService.java
Labels: 🏄🏻‍♂️ feature

#24 ✨ feat : 이벤트 참여 API 구현
  src/main/java/com/nexters/pinataserver/common/util/RandomNumberGenerator.java
  src/main/java/com/nexters/pinataserver/event/controller/EventController.java
  src/main/java/com/nexters/pinataserver/event/domain/Event.java
  src/main/java/com/nexters/pinataserver/event/domain/EventRepository.java
  src/main/java/com/nexters/pinataserver/event/domain/EventType.java
  src/main/java/com/nexters/pinataserver/event/dto/request/ParticipateEventRequest.java
  src/main/java/com/nexters/pinataserver/event/service/EventParticipateService.java
  src/main/java/com/nexters/pinataserver/event/service/EventReadService.java
  src/main/java/com/nexters/pinataserver/event/service/EventValidateService.java
  src/main/java/com/nexters/pinataserver/event_history/domain/EventHistoryRepository.java
Labels: 🏄🏻‍♂️ feature

#27 [feature] 내가 생성한 이벤트 목록 조회
  src/main/java/com/nexters/pinataserver/event/controller/EventController.java
  src/main/java/com/nexters/pinataserver/event/domain/EventsRepository.java
  src/main/java/com/nexters/pinataserver/event/dto/response/EventResponse.java
  src/main/java/com/nexters/pinataserver/event/service/EventReadService.java
Labels: 🏄🏻‍♂️ feature

#35 [feature] 이벤트 목록 API 구현
  src/main/java/com/nexters/pinataserver/common/dto/response/DatePatternEnum.java
  src/main/java/com/nexters/pinataserver/common/interceptor/JwtInterceptor.java
  src/main/java/com/nexters/pinataserver/common/util/ImageUtil.java
  src/main/java/com/nexters/pinataserver/event/controller/EventController.java
  src/main/java/com/nexters/pinataserver/event/domain/Event.java
  src/main/java/com/nexters/pinataserver/event/domain/EventRepository.java
  src/main/java/com/nexters/pinataserver/event/domain/EventRepositoryCustom.java
  src/main/java/com/nexters/pinataserver/event/domain/EventRepositoryImpl.java
  src/main/java/com/nexters/pinataserver/event/domain/EventStatus.java
  src/main/java/com/nexters/pinataserver/event/domain/EventsRepository.java
  src/main/java/com/nexters/pinataserver/event/dto/response/EventResponse.java
  src/main/java/com/nexters/pinataserver/event/dto/response/OrganizersEventResponse.java
  src/main/java/com/nexters/pinataserver/event/dto/response/ParticipationEventResponse.java
  src/main/java/com/nexters/pinataserver/event/service/EventReadService.java
Labels: 🏄🏻‍♂️ feature

#37 fix: 이벤트 참여 시 아이템 수령여부 변경 (#36)
  src/main/java/com/nexters/pinataserver/event/domain/EventDateTime.java
  src/main/java/com/nexters/pinataserver/event/domain/EventItem.java
  src/main/java/com/nexters/pinataserver/event/service/EventParticipateService.java
  src/main/java/com/nexters/pinataserver/event/service/EventValidateService.java
Labels: 🐛 bug

#42 feat: 이미지 다운로드 API를 구현한다 (#41)
  src/main/java/com/nexters/pinataserver/common/exception/e5xx/FileDownloadException.java
  src/main/java/com/nexters/pinataserver/common/image/ImageUploadController.java
  src/main/java/com/nexters/pinataserver/common/image/ImageUploadService.java
Labels: 🏄🏻‍♂️ feature

#43 feat: 이미지 다운로드 시 바이너리 데이터를 내려주도록 수정한다 (#41)
  src/main/java/com/nexters/pinataserver/common/image/ImageDownloadResponse.java
  src/main/java/com/nexters/pinataserver/common/image/ImageUploadController.java
  src/main/java/com/nexters/pinataserver/common/image/ImageUploadService.java
Labels: 🏄🏻‍♂️ feature
